version: '3.8'

services:

  # === Infrastructure ===

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  # === Config & Service Discovery ===

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - kafka

  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"

  # === Microservices ===

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - service-registry
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - service-registry

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - config-server
      - service-registry

  match-engine-service:
    build: ./match-engine-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - config-server
      - service-registry

  trade-service:
    build: ./trade-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - config-server
      - service-registry

  audit-service:
    build: ./audit-service
    ports:
      - "8086:8086"
    depends_on:
      - kafka
      - mongodb
      - config-server
      - service-registry

  portfolio-service:
    build: ./portfolio-service
    ports:
      - "8087:8087"
    depends_on:
      - kafka
      - config-server
      - service-registry

